/// Flutter icons Github
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Github
///      fonts:
///       - asset: fonts/Github.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Github {
  Github._();

  static const _kFontFam = 'Github';
  static const _kFontPkg = null;

  static const IconData github_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
